# Generated by Django 5.2.14 on 2026-06-17 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(default=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(default=170)),
                ('weight_kg', models.FloatField(default=70.0)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Active'), ('very_active', 'Very active')], default='moderate', max_length=20)),
                ('goal', models.CharField(choices=[('lose', 'Lose weight'), ('maintain', 'Maintain weight'), ('gain', 'Gain weight')], default='maintain', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
